<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LedgerLens.PortfolioCore.Application\LedgerLens.PortfolioCore.Application.csproj" />
    <ProjectReference Include="..\LedgerLens.PortfolioCore.Database\LedgerLens.PortfolioCore.Database.csproj" />
    <ProjectReference Include="..\LedgerLens.PortfolioCore.Domain\LedgerLens.PortfolioCore.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.NATS.Net" />
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>
</Project>
